---
title: "Project1"
author: "Aria Hamidi"
date: "2/8/2021"
output: html_document
---

#Importing the dataset

loseit = read.csv("~/Desktop/loseit.csv")
loseit = data.frame(Loss,Diet)

##Calculating the means of each type of diet
group.means = by(loseit$Loss,loseit$Diet,mean)
group.means
##Scatter plot for showing the amount of weight loss in different groups
plot(group.means,xaxt = "n",pch = 19,col = "red",xlab = "Three different diets",ylab = "Average of the weight loss",main = "Losing weight by group",type = "b") 




##Visualizing the data by creating a boxplot
boxplot(loseit$Loss ~ loseit$Diet, main = "Weight loss by group",ylab = "Weight Loss")



##Summarizing the data
group.means =  by(loseit$Loss,loseit$Diet,mean)
group.sds = by(loseit$Loss,loseit$Diet,sd)
group.nis = by(loseit$Loss,loseit$Diet,length)
the.summary = rbind(group.means,group.sds,group.nis)
the.summary = round(the.summary,digits = 4)
colnames(the.summary) = names(group.means)
rownames(the.summary) = c("Means","Std. Dev","Sample Size")
the.summary




#Calculating the five-number summary
fivenum(loseit$Loss)







#DIAGNOSTICS


#Identifying values for a cut off
CO3 = which((loseit$Diet=="A" & loseit$Loss > 7) | (loseit$Diet=="B" & loseit$Loss < -2))
CO3
the.model = lm(Loss ~ Diet, data = loseit)




#semi-studentized model
loseit$ei = the.model$residuals
nt = nrow(loseit) #Calculates the total sample size
a = length(unique(loseit$Diet)) #Calculates the value of a
SSE = sum(loseit$ei^2) #Sums and squares the errors (finds SSE)
MSE = SSE/(nt-a) #Finds MSE
eij.star = the.model$residuals/sqrt(MSE)
alpha = 0.05
t.cutoff= qt(1-alpha/(2*nt), nt-a)
CO.eij = which(abs(eij.star) > t.cutoff)
CO.eij #No outliers via this method

rij = rstandard(the.model) #studentized method
CO.rij = which(abs(rij) > t.cutoff)
CO.rij #No outliers via this method

outliers = CO3
outliers
new.data = loseit[-outliers,]
new.model = lm(Loss ~ Diet,data = new.data)
new.model

new.data 





qqnorm(new.model$residuals)
qqline(new.model$residuals)

ei = new.model$residuals
the.SWtest = shapiro.test(ei)
the.SWtest #Since our p-value was relatively large, we fail to reject the null, and support that our data is normally distributed at any reasonable significance level (1%, 5%, 10%).

library(ggplot2)
qplot(Diet, ei, data = new.data) + ggtitle("Errors vs. Groups") + xlab("Groups") + ylab("Errors") + geom_hline(yintercept = 0,col = "purple") #Since our vertical spread is relatively equal with each other, we can say that there is equal variance between them. 




group.means = by(new.data$Loss,new.data$Diet,mean)
group.sds = by(new.data$Loss,new.data$Diet,sd)
group.nis = by(new.data$Loss,new.data$Diet,length)
the.summary = rbind(group.means,group.sds,group.nis)
the.summary = round(the.summary,digits = 4)
colnames(the.summary) = names(group.means)
rownames(the.summary) = c("Means","Std. Dev","Sample Size")
the.summary

anova.table = anova(new.model)
anova.table

F.stat = anova.table[1,4]
F.stat

p.val = anova.table[1,5]
p.val #Because it is very less than any reasonable significance level, we reject the null hypothesis

#Finding a power of the test
give.me.power = function(ybar,ni,MSE,alpha){
  a = length(ybar) # Finds a
  nt = sum(ni) #Finds the overall sample size
  overall.mean = sum(ni*ybar)/nt # Finds the overall mean
  phi = (1/sqrt(MSE))*sqrt( sum(ni*(ybar - overall.mean)^2)/a) #Finds the books value of phi
  phi.star = a *phi^2 #Finds the value of phi we will use for R
  Fc = qf(1-alpha,a-1,nt-a) #The critical value of F, use in R’s function
  power = 1 - pf(Fc, a-1, nt-a, phi.star)# The power, calculated using a non-central F
  return(power)
}

MSE = anova.table[2,3]

the.power = give.me.power(group.means,group.nis,MSE,0.05)
the.power


give.me.CI = function(ybar,ni,ci,MSE,multiplier){
  if(sum(ci) != 0 & sum(ci !=0 ) != 1){
    return("Error - you did not input a valid contrast")
  } else if(length(ci) != length(ni)){
    return("Error - not enough contrasts given")
  }
  else{
    estimate = sum(ybar*ci)
    SE = sqrt(MSE*sum(ci^2/ni))
    CI = estimate + c(-1,1)*multiplier*SE
    result = c(estimate,CI)
    names(result) = c("Estimate","Lower Bound","Upper Bound")
    return(result)
  }
}

nt = sum(group.nis)
a = length(group.means)
alpha = 0.05

Tuk = qtukey(1-alpha,a,nt-a)/sqrt(2)
Tuk
S = sqrt((a-1)*qf(1-alpha, a-1, nt-a))
S
g=3
B = qt(1-alpha/(2*g),nt-a)
B

#Interval for C-A
c1 = c(-1,0,1)
give.me.CI(group.means,group.nis,c1,MSE,Tuk)

#Interval for C-B
c2 = c(0,-1,1)
give.me.CI(group.means,group.nis,c2,MSE,Tuk)

#Interval for B-A
c3 = c(-1,1,0)
give.me.CI(group.means,group.nis,c3,MSE,Tuk)






